# Generated by Django 5.0.14 on 2026-09-10 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_cost', models.DecimalField(decimal_places=2, help_text='Wholesale cost offered by provider (Commercial secret).', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_NEGOTIATION', 'Under Negotiation'), ('ACCEPTED_BY_BROKER', 'Accepted by Broker'), ('DECLINED_BY_BROKER', 'Declined by Broker'), ('SUPERSEDED', 'Superseded by Revised Quote')], default='SUBMITTED', max_length=25)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_quotes', to='fleet.vehicle')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounts.providercompany')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_cost', models.DecimalField(decimal_places=2, help_text='Protected: Provider cost hidden from corporate customer.', max_digits=12)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Protected: FlexyRide commission/margin hidden from corporate customer.', max_digits=12)),
                ('final_customer_price', models.DecimalField(decimal_places=2, help_text='Final price visible to and charged to corporate customer.', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted by Customer'), ('DECLINED', 'Declined by Customer'), ('CHANGE_REQUESTED', 'Customer Requested Change')], default='DRAFT', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer_decision_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Customer notes, change request details, or decline reason.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_customer_quotes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_quotes', to='bookings.transportationrequest')),
                ('selected_provider_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_quotations', to='quotations.providerquote')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Request Sent to Provider'), ('RESPONDED', 'Provider Responded'), ('DECLINED', 'Provider Declined'), ('NO_RESPONSE', 'No Response'), ('EXPIRED', 'Expired')], default='SENT', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='accounts.providercompany')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_quote_requests', to='bookings.transportationrequest')),
            ],
        ),
        migrations.AddField(
            model_name='providerquote',
            name='quote_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotations.providerquoterequest'),
        ),
        migrations.CreateModel(
            name='QuoteNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_counter_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_negotiations', to=settings.AUTH_USER_MODEL)),
                ('provider_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='quotations.providerquote')),
            ],
        ),
    ]
