# Generated by Django 6.1.1 on 2026-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive tier name (e.g. Standard SUV 25%, VIP Luxury 30%)', max_length=100)),
                ('vehicle_category', models.CharField(blank=True, choices=[('SEDAN', 'Standard Sedan'), ('EXECUTIVE', 'Executive Saloon'), ('SUV', 'SUV / 4x4'), ('VAN', 'Passenger Van'), ('MINIBUS', 'Minibus / Shuttle'), ('COASTER_BUS', 'Coaster Bus'), ('LUXURY', 'VIP / Luxury Vehicle')], help_text='Leave blank to match all vehicle categories', max_length=30, null=True)),
                ('min_distance_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum distance for tier in km', max_digits=8)),
                ('max_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for open-ended maximum distance', max_digits=8, null=True)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='FlexyRide commission percentage to apply (e.g. 25.00 for 25%)', max_digits=5)),
                ('min_margin_amount', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum guaranteed FlexyRide commission in GHS', max_digits=10)),
                ('auto_dispatch_quote', models.BooleanField(default=True, help_text='If enabled, accepting an RFQ instantly generates and dispatches the customer quote without manual broker delay.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this commission tier is actively evaluated')),
                ('priority', models.PositiveIntegerField(default=10, help_text='Evaluation priority: higher priority rules match first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Percentage Tier',
                'verbose_name_plural': 'Commission Percentage Tiers',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
