# Generated by Django 6.1.1 on 2026-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_commissiontier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerquote',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_NEGOTIATION', 'Under Negotiation'), ('ACCEPTED_BY_BROKER', 'Accepted by FlexyRide Corporate'), ('DECLINED_BY_BROKER', 'Declined by FlexyRide Corporate'), ('SUPERSEDED', 'Superseded by Revised Quote')], default='SUBMITTED', max_length=25),
        ),
    ]
