# Generated by Django 6.1.1 on 2026-09-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Budget allocation code for expense tracking.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='department',
            field=models.CharField(blank=True, help_text="Employee's department within the company.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corporatecustomer',
            name='billing_type',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('CREDIT', 'Credit Account'), ('INVOICE', 'Monthly Invoice')], default='PREPAID', help_text='How this customer is billed.', max_length=20),
        ),
        migrations.AddField(
            model_name='corporatecustomer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum outstanding credit balance allowed.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='corporatecustomer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30, help_text='Net payment terms in days (e.g. 30, 60, 90).'),
        ),
        migrations.AddField(
            model_name='corporatecustomer',
            name='preferred_currency',
            field=models.CharField(default='UGX', help_text='Preferred billing currency.', max_length=10),
        ),
        migrations.AddField(
            model_name='providercompany',
            name='response_time_avg',
            field=models.DurationField(blank=True, help_text='Average response time to quote requests.', null=True),
        ),
        migrations.AddField(
            model_name='providercompany',
            name='service_area',
            field=models.TextField(blank=True, help_text='Geographic areas this provider covers (e.g. Kampala, Entebbe, Jinja).', null=True),
        ),
        migrations.AddField(
            model_name='providercompany',
            name='specializations',
            field=models.CharField(blank=True, help_text='Comma-separated specializations (e.g. airport,executive,events).', max_length=255, null=True),
        ),
    ]
