# Generated by Django 6.1.1 on 2026-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_corporatecustomer_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercompany',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, help_text='Paystack Subaccount code (e.g. ACCT_xxxxx) for automated payout splits.', max_length=50, null=True),
        ),
    ]
