# Generated by Django 6.1.1 on 2026-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_providercompany_paystack_subaccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercompany',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number or MoMo number for payouts.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providercompany',
            name='settlement_bank',
            field=models.CharField(blank=True, help_text='Bank name, Bank Code, or Mobile Money network (e.g. MTN, VOD, Access Bank).', max_length=100, null=True),
        ),
    ]
