# Generated by Django 5.0.14 on 2026-09-10 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('PROVIDER', 'Provider Company'), ('VEHICLE', 'Vehicle'), ('DRIVER', 'Driver')], help_text='Entity type this compliance document belongs to.', max_length=20)),
                ('document_type', models.CharField(choices=[('BUSINESS_LICENSE', 'Business License / Registration'), ('TAX_CERTIFICATE', 'Tax Compliance Certificate'), ('INSURANCE', 'Vehicle Insurance Policy'), ('ROADWORTHINESS', 'Roadworthiness Certificate'), ('DRIVERS_LICENSE', "Driver's License"), ('POLICE_CLEARANCE', 'Police Background Check'), ('OTHER', 'Other Operational Document')], max_length=30)),
                ('document_file', models.FileField(upload_to='compliance_docs/%Y/%m/')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='fleet.driver')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='accounts.providercompany')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='fleet.vehicle')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_compliance_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
