# Generated by Django 6.1.1 on 2026-09-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyemployee_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecustomer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Corporate company brand logo.', null=True, upload_to='company_logos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='corporatecustomer',
            name='preferred_currency',
            field=models.CharField(default='GHS', help_text='Preferred billing currency.', max_length=10),
        ),
        migrations.AlterField(
            model_name='providercompany',
            name='service_area',
            field=models.TextField(blank=True, help_text='Geographic areas this provider covers (e.g. Accra, Tema, Kumasi, Takoradi).', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Corporate Customer'), ('EMPLOYEE_REQUESTER', 'Employee / Requester'), ('BROKER', 'FlexyRide Broker / Staff'), ('PROVIDER_ADMIN', 'Provider Administrator'), ('DRIVER', 'Driver'), ('SYSTEM_ADMIN', 'System Administrator')], default='CUSTOMER', help_text='Primary functional role of the user within FlexyRide Corporate.', max_length=30),
        ),
    ]
