"""
Django settings for flexyride_corporate project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / 'apps'))

# Load environment variables from .env if present
env_file = BASE_DIR / '.env'
if env_file.is_file():
    try:
        from dotenv import load_dotenv
        load_dotenv(env_file)
    except ImportError:
        with open(env_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    k, v = line.split('=', 1)
                    k = k.strip()
                    v = v.strip().strip("'\"")
                    if k not in os.environ:
                        os.environ[k] = v

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-+yi0h8#m6kgfipb-tfeyy7iglz*xo_)2y9+o@3e5eq2j(^cxlg')
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
if allowed_hosts_env and allowed_hosts_env != '*':
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['*']

# Ensure production domain is always included in allowed hosts
for host in ['test-corporate.flexyridegh.com', '.flexyridegh.com', 'localhost', '127.0.0.1', '0.0.0.0']:
    if '*' not in ALLOWED_HOSTS and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Reverse proxy SSL Header (tells Django requests are HTTPS through Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF Trusted Origins for HTTPS
csrf_trusted_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_trusted_origins_env:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_trusted_origins_env.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://test-corporate.flexyridegh.com',
        'https://*.flexyridegh.com',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]



# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Corporate Applications
    'accounts',
    'compliance',
    'fleet',
    'bookings',
    'quotations',
    'payments',
    'feedback',
    'notifications',
    'sla',
    'portal',
]

AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.StaffRoleEnforcementMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portal.context_processors.google_maps',
                'portal.context_processors.corporate_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

LOGIN_URL = 'portal_login'
LOGIN_REDIRECT_URL = '/admin/'

# Google Maps API Configuration
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# Email Service Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'FlexyRide Corporate <dispatch@flexyride.com>')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)



# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# DJANGO UNFOLD CONFIGURATION
# ==============================================================================
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "FlexyRide Corporate",
    "SITE_HEADER": "FlexyRide Corporate Console",
    "SITE_SUBHEADER": "Executive Operations & Dispatch Governance",
    "SITE_URL": "/portal/broker/",
    "SITE_ICON": {
        "light": lambda request: "/static/portal/img/logo_icon.png",
        "dark": lambda request: "/static/portal/img/logo_icon.png",
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/portal/img/logo_icon.png",
        "dark": lambda request: "/static/portal/img/logo_icon.png",
    },
    "COLORS": {
        "primary": {
            "50": "244 249 237",
            "100": "231 243 216",
            "200": "208 232 179",
            "300": "178 217 134",
            "400": "140 198 63",
            "500": "120 178 45",
            "600": "93 142 34",
            "700": "71 108 28",
            "800": "58 87 26",
            "900": "49 73 24",
            "950": "25 40 11",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Broker Portal"),
                        "icon": "open_in_new",
                        "link": reverse_lazy("portal_broker_workspace"),
                    },
                ],
            },
            {
                "title": _("Accounts & Access"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": _("Corporate Customers"),
                        "icon": "business",
                        "link": reverse_lazy("admin:accounts_corporatecustomer_changelist"),
                    },
                    {
                        "title": _("Company Employees"),
                        "icon": "badge",
                        "link": reverse_lazy("admin:accounts_companyemployee_changelist"),
                    },
                    {
                        "title": _("Provider Companies"),
                        "icon": "storefront",
                        "link": reverse_lazy("admin:accounts_providercompany_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Dispatch & Bookings"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Transportation Requests"),
                        "icon": "commute",
                        "link": reverse_lazy("admin:bookings_transportationrequest_changelist"),
                    },
                    {
                        "title": _("Vehicle Assignments"),
                        "icon": "assignment_turned_in",
                        "link": reverse_lazy("admin:bookings_vehicleassignment_changelist"),
                    },
                    {
                        "title": _("Cancellation Requests"),
                        "icon": "cancel",
                        "link": reverse_lazy("admin:bookings_cancellationrequest_changelist"),
                    },
                ],
            },
            {
                "title": _("Quotations & RFQs"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Customer Quotes"),
                        "icon": "request_quote",
                        "link": reverse_lazy("admin:quotations_customerquote_changelist"),
                    },
                    {
                        "title": _("Provider Quotes"),
                        "icon": "price_change",
                        "link": reverse_lazy("admin:quotations_providerquote_changelist"),
                    },
                    {
                        "title": _("Provider Quote Requests"),
                        "icon": "contact_mail",
                        "link": reverse_lazy("admin:quotations_providerquoterequest_changelist"),
                    },
                ],
            },
            {
                "title": _("Fleet Operations"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Fleet Vehicles"),
                        "icon": "local_taxi",
                        "link": reverse_lazy("admin:fleet_vehicle_changelist"),
                    },
                    {
                        "title": _("Drivers"),
                        "icon": "airline_seat_recline_normal",
                        "link": reverse_lazy("admin:fleet_driver_changelist"),
                    },
                ],
            },
            {
                "title": _("Compliance & Risk"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Compliance Documents"),
                        "icon": "verified_user",
                        "link": reverse_lazy("admin:compliance_compliancedocument_changelist"),
                    },
                ],
            },
            {
                "title": _("Finance & Billing"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Invoices"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:payments_invoice_changelist"),
                    },
                    {
                        "title": _("Payment Transactions"),
                        "icon": "paid",
                        "link": reverse_lazy("admin:payments_paymenttransaction_changelist"),
                    },
                ],
            },
            {
                "title": _("Feedback & Performance"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Journey Ratings"),
                        "icon": "star",
                        "link": reverse_lazy("admin:feedback_journeyrating_changelist"),
                    },
                    {
                        "title": _("Booking Timelines"),
                        "icon": "timeline",
                        "link": reverse_lazy("admin:feedback_bookingtimeline_changelist"),
                    },
                    {
                        "title": _("SLA Metrics"),
                        "icon": "speed",
                        "link": reverse_lazy("admin:sla_slametric_changelist"),
                    },
                ],
            },
        ],
    },
}

# --------------------------------------------------------------------------
# Paystack Payment Gateway Configuration
# --------------------------------------------------------------------------
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', 'pk_test_d3a8258b3f46f497743956e1871234567890abcd')
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', 'sk_test_e7b9148c2e55a586632845e2760987654321dcba')
PAYSTACK_CURRENCY = os.environ.get('PAYSTACK_CURRENCY', 'GHS')

# --------------------------------------------------------------------------
# Web Push (VAPID) Configuration (100% Free Browser Native Push)
# --------------------------------------------------------------------------
VAPID_PUBLIC_KEY = os.environ.get(
    'VAPID_PUBLIC_KEY',
    'BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuBkr3qBUYIHBQFLXYp5Nksh8U'
)
VAPID_PRIVATE_KEY = os.environ.get(
    'VAPID_PRIVATE_KEY',
    'AA9hK5Uf_o6wK1hVbZpE5c0Q-v1M7K5bN9fD6v3xR9Y'
)
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', 'mailto:dispatch@flexyride.com')

# --------------------------------------------------------------------------
# Celery & Background Scheduled Workers (US-11, US-103, US-109, US-110)
# --------------------------------------------------------------------------
from celery.schedules import crontab

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    # 1. Generate concrete journey occurrences from recurring templates (daily at 01:00 AM)
    'generate-recurring-bookings-daily': {
        'task': 'bookings.tasks.generate_recurring_bookings_task',
        'schedule': crontab(hour=1, minute=0),
    },
    # 2. Check compliance document expiration warnings at 30, 15, and 7 days (daily at 06:00 AM)
    'check-document-expirations-daily': {
        'task': 'compliance.tasks.check_document_expirations_task',
        'schedule': crontab(hour=6, minute=0),
    },
    # 3. Detect SLA response & dispatch breaches (every 30 minutes)
    'detect-sla-breaches-periodic': {
        'task': 'sla.tasks.detect_sla_breaches_task',
        'schedule': crontab(minute='*/30'),
    },
}

# --------------------------------------------------------------------------
# Production Logging Configuration (Logs tracebacks to console / journalctl)
# --------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



