# Generated by Django 5.0.14 on 2026-09-10 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, help_text='Human readable unique request reference, e.g. FRC-2026-00001', max_length=50, unique=True)),
                ('internal_approval_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING_APPROVAL', 'Pending Internal Approval'), ('APPROVED', 'Approved by Company'), ('REJECTED', 'Rejected by Company')], default='NOT_REQUIRED', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('internal_rejection_reason', models.TextField(blank=True, null=True)),
                ('journey_type', models.CharField(choices=[('ONE_WAY', 'One-Way Journey'), ('RETURN', 'Return Journey'), ('HOURLY', 'Hourly Hire'), ('FULL_DAY', 'Full-Day Hire'), ('MULTI_DAY', 'Multi-Day Hire'), ('MULTI_VEHICLE', 'Multiple Vehicles'), ('RECURRING', 'Recurring Transportation'), ('AIRPORT_TRANSFER', 'Airport Transfer'), ('AIRPORT_MEET_GREET', 'Airport Meet & Greet'), ('EVENT', 'Event / Conference Transportation')], default='ONE_WAY', max_length=30)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_address', models.TextField()),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('departure_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_datetime', models.DateTimeField(blank=True, null=True)),
                ('airport_name', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_vehicle_category', models.CharField(choices=[('SEDAN', 'Sedan'), ('EXECUTIVE', 'Executive'), ('SUV', 'Suv'), ('VAN', 'Van'), ('MINIBUS', 'Minibus'), ('COASTER_BUS', 'Coaster Bus'), ('LUXURY', 'Luxury')], default='SEDAN', max_length=30)),
                ('vehicles_requested_count', models.PositiveIntegerField(default=1)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('luggage_requirements', models.TextField(blank=True, null=True)),
                ('accessibility_required', models.BooleanField(default=False)),
                ('child_seats_count', models.PositiveIntegerField(default=0)),
                ('executive_vehicle_required', models.BooleanField(default=False)),
                ('additional_stops_notes', models.TextField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('AWAITING_INTERNAL_APPROVAL', 'Awaiting Internal Approval'), ('APPROVED_BY_COMPANY', 'Approved by Company'), ('REJECTED_BY_COMPANY', 'Rejected by Company'), ('RECEIVED_BY_FLEXYRIDE', 'Received by FlexyRide'), ('BEING_ARRANGED', 'Being Arranged'), ('QUOTE_AVAILABLE', 'Quote Available'), ('AWAITING_CUSTOMER_ACCEPTANCE', 'Awaiting Customer Acceptance'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Driver/Vehicle Assigned'), ('DRIVER_EN_ROUTE', 'Driver En Route'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('PASSENGER_ONBOARD', 'Passenger Onboard'), ('TRIP_IN_PROGRESS', 'Trip In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUEST_SUBMITTED', max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_corporate_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.corporatecustomer')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CUSTOM', 'Custom Schedule')], default='WEEKLY', max_length=20)),
                ('days_of_week', models.CharField(help_text='Comma separated days, e.g. MON,WED,FRI', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='bookings.transportationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique access token allowing passenger tracking without account registration.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.transportationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('PASSENGER_ONBOARD', 'Passenger Onboard'), ('TRIP_IN_PROGRESS', 'Trip In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REPLACED', 'Replaced')], default='ASSIGNED', max_length=25)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('replacement_reason', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.driver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='bookings.transportationrequest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.vehicle')),
            ],
        ),
    ]
