# Generated by Django 6.1.1 on 2026-09-10 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationrequest',
            name='cancellation_policy_tier',
            field=models.CharField(blank=True, help_text='Which cancellation policy tier applies to this booking.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportationrequest',
            name='customer_reference',
            field=models.CharField(blank=True, help_text="Customer's internal PO or reference number.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportationrequest',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated journey distance in kilometres.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transportationrequest',
            name='priority_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('STANDARD', 'Standard'), ('URGENT', 'Urgent')], default='STANDARD', help_text='Urgency level of this request.', max_length=20),
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for cancellation.')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged for cancellation based on policy tier.', max_digits=12)),
                ('fee_waived', models.BooleanField(default=False, help_text='Whether the cancellation fee has been waived by FlexyRide.')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount refunded to customer.', max_digits=12)),
                ('policy_applied', models.CharField(blank=True, help_text='Name/tier of cancellation policy applied.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='bookings.transportationrequest')),
            ],
        ),
    ]
