# Generated by Django 6.1.1 on 2026-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_transportationrequest_cancellation_policy_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationrequest',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrequest',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrequest',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transportationrequest',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
