from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.RoleBasedLoginView.as_view(), name='portal_login'),
    path('logout/', views.portal_logout_view, name='portal_logout'),
    path('signup/', views.customer_signup_view, name='portal_signup'),
    path('register/', views.customer_signup_view, name='portal_register'),
    path('', views.landing_page_view, name='landing_page'),
    path('solutions/', views.solutions_view, name='portal_solutions'),
    path('how-it-works/', views.how_it_works_view, name='portal_how_it_works'),
    path('fleet-categories/', views.fleet_categories_view, name='portal_fleet_categories'),
    path('compliance-safety/', views.compliance_safety_view, name='portal_compliance_safety'),
    path('dashboard/', views.dashboard_view, name='portal_dashboard'),
    path('profile/', views.customer_profile_view, name='portal_customer_profile'),
    path('portal/profile/', views.customer_profile_view, name='portal_customer_profile_alt'),
    path('requests/new/', views.new_request_view, name='portal_new_request'),
    path('requests/<str:request_id>/success/', views.request_success_view, name='portal_request_success'),
    path('requests/<str:request_id>/details/', views.request_details_view, name='portal_request_details'),
    path('requests/<str:request_id>/quote/', views.quote_ready_view, name='portal_quote_ready'),
    path('requests/<str:request_id>/pay/', views.payment_view, name='portal_payment'),
    path('requests/<str:request_id>/payment-success/', views.payment_success_view, name='portal_payment_success'),
    path('bookings/<str:booking_id>/confirmed/', views.confirmed_booking_view, name='portal_confirmed_booking'),
    path('bookings/<str:booking_id>/track/', views.live_journey_view, name='portal_live_journey'),
    path('trips/upcoming/', views.upcoming_trips_view, name='portal_upcoming_trips'),
    path('trips/history/', views.trip_history_view, name='portal_trip_history'),
    path('invoices/', views.customer_invoices_view, name='portal_customer_invoices'),
    # Broker Portal Dedicated Independent Routes
    path('broker/', views.broker_overview_view, name='portal_broker_workspace'),
    path('broker/overview/', views.broker_overview_view, name='portal_broker_overview'),
    path('broker/rfqs/', views.broker_rfqs_view, name='portal_broker_rfqs'),
    path('broker/quotes/', views.broker_quotes_view, name='portal_broker_quotes'),
    path('broker/dispatches/', views.broker_dispatches_view, name='portal_broker_dispatches'),
    path('broker/providers/', views.broker_providers_view, name='portal_broker_providers'),
    path('broker/customers/', views.broker_customers_view, name='portal_broker_customers'),
    path('broker/financials/', views.broker_financials_view, name='portal_broker_financials'),
    path('provider/', views.provider_overview_view, name='portal_provider_workspace'),
    path('provider/overview/', views.provider_overview_view, name='portal_provider_overview'),
    path('provider/dispatches/', views.provider_dispatches_view, name='portal_provider_dispatches'),
    path('provider/rfqs/', views.provider_rfqs_view, name='portal_provider_rfqs'),
    path('provider/fleet/', views.provider_fleet_view, name='portal_provider_fleet'),
    path('provider/drivers/', views.provider_drivers_view, name='portal_provider_drivers'),
    path('provider/compliance/', views.provider_compliance_view, name='portal_provider_compliance'),
    path('provider/payouts/', views.provider_payouts_view, name='portal_provider_payouts'),
    path('provider/company/', views.provider_company_view, name='portal_provider_company'),
    path('provider/profile/', views.provider_profile_view, name='portal_provider_profile'),
    path('passenger/track/<str:tracking_token>/', views.passenger_tracking_view, name='portal_passenger_tracking'),
    path('admin-metrics/', views.admin_metrics_view, name='portal_admin_metrics'),
    # Financial, Webhook & Print Routes
    path('payments/paystack/webhook/', views.paystack_webhook_view, name='portal_paystack_webhook'),
    path('receipts/<str:receipt_ref>/print/', views.receipt_printable_view, name='portal_receipt_printable'),
    path('invoices/<str:invoice_num>/print/', views.invoice_printable_view, name='portal_invoice_printable'),
    # Web Push, Ratings & Support APIs
    path('api/webpush/subscribe/', views.webpush_subscribe_api, name='portal_webpush_subscribe'),
    path('api/notifications/', views.notifications_api, name='portal_notifications_api'),
    path('trips/rate/', views.submit_journey_rating_view, name='portal_submit_journey_rating'),
    path('support/report-issue/', views.report_support_issue_view, name='portal_report_support_issue'),
]

