# Generated by Django 6.1.1 on 2026-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_driver_languages_spoken_driver_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SEDAN', 'Standard Sedan'), ('EXECUTIVE', 'Executive Saloon'), ('SUV', 'SUV / 4x4'), ('VAN', 'Passenger Van'), ('MINIBUS', 'Minibus / Shuttle'), ('COASTER_BUS', 'Coaster Bus'), ('LUXURY', 'VIP / Luxury Vehicle')], help_text='Standard vehicle category class', max_length=30, unique=True)),
                ('display_name', models.CharField(help_text='e.g. SUV / 4x4 (Executive Fleet)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Vehicle specifications, passenger class, and standards')),
                ('base_wholesale_rate', models.DecimalField(decimal_places=2, help_text='Broker-provided baseline wholesale payout for this category in GHS', max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional per-km payout guideline in GHS/km', max_digits=8)),
                ('daily_charter_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Full-day charter wholesale benchmark in GHS', max_digits=10)),
                ('min_seating_capacity', models.PositiveIntegerField(default=4, help_text='Minimum passenger seating capacity')),
                ('recommended_models', models.CharField(blank=True, help_text='e.g. Toyota Prado, Pajero, Fortuner', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is actively open for provider listing')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Order in dropdowns and pricing schedules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Category & Pricing Rate',
                'verbose_name_plural': 'Vehicle Categories & Pricing Rates',
                'ordering': ['display_order', 'category'],
            },
        ),
        migrations.AlterField(
            model_name='driver',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma-separated languages (e.g. English,Twi,Ga,Hausa).', max_length=255, null=True),
        ),
    ]
