# Generated by Django 5.0.14 on 2026-09-10 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('OFF_DUTY', 'Off Duty'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant & Approved'), ('NON_COMPLIANT', 'Non-Compliant / Expired'), ('PENDING_REVIEW', 'Pending Review')], default='PENDING_REVIEW', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='accounts.providercompany')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('SEDAN', 'Standard Sedan'), ('EXECUTIVE', 'Executive Saloon'), ('SUV', 'SUV / 4x4'), ('VAN', 'Passenger Van'), ('MINIBUS', 'Minibus / Shuttle'), ('COASTER_BUS', 'Coaster Bus'), ('LUXURY', 'VIP / Luxury Vehicle')], default='SEDAN', max_length=30)),
                ('seating_capacity', models.PositiveIntegerField(default=4)),
                ('luggage_capacity', models.CharField(blank=True, help_text='e.g. 3 large suitcases, 2 small bags', max_length=100, null=True)),
                ('has_accessibility', models.BooleanField(default=False, help_text='Wheelchair accessible vehicle.')),
                ('has_child_seat', models.BooleanField(default=False, help_text='Equipped with child safety seats.')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned to Trip'), ('MAINTENANCE', 'In Maintenance'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant & Approved'), ('NON_COMPLIANT', 'Non-Compliant / Expired'), ('PENDING_REVIEW', 'Pending Review')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.providercompany')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_photos/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fleet.vehicle')),
            ],
        ),
    ]
