# Generated by Django 6.1.1 on 2026-09-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma-separated languages (e.g. English,Luganda,Swahili).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, help_text='Driver profile photo.', null=True, upload_to='driver_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='water_provided',
            field=models.BooleanField(default=False, help_text='Equipped with child safety seats.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wifi_available',
            field=models.BooleanField(default=False, help_text='Vehicle has WiFi available.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_child_seat',
            field=models.BooleanField(default=False),
        ),
    ]
