# Generated by Django 6.1.1 on 2026-09-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_companyemployee_cost_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('RESPONSE_TIME', 'Quote Response Time'), ('QUALITY_SCORE', 'Service Quality Score'), ('ON_TIME_RATE', 'On-Time Arrival Rate'), ('COMPLETION_RATE', 'Trip Completion Rate'), ('CUSTOMER_SATISFACTION', 'Customer Satisfaction Score')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, help_text='Metric value (percentage, score, or duration in minutes).', max_digits=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_metrics', to='accounts.providercompany')),
            ],
            options={
                'verbose_name': 'SLA Metric',
                'verbose_name_plural': 'SLA Metrics',
                'ordering': ['-measured_at'],
            },
        ),
    ]
