# Generated by Django 6.1.1 on 2026-09-10 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_transportationrequest_cancellation_policy_tier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], default='IN_APP', max_length=10)),
                ('notification_type', models.CharField(choices=[('BOOKING_UPDATE', 'Booking Status Update'), ('QUOTE_READY', 'Quote Ready'), ('QUOTE_EXPIRING', 'Quote Expiring Soon'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_EN_ROUTE', 'Driver En Route'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('TRIP_COMPLETED', 'Trip Completed'), ('CANCELLATION', 'Booking Cancelled'), ('COMPLIANCE_EXPIRY', 'Compliance Document Expiring'), ('APPROVAL_REQUIRED', 'Internal Approval Required'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger_info', models.ForeignKey(blank=True, help_text='Passenger recipient for accountless passengers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.passengerinfo')),
                ('recipient', models.ForeignKey(blank=True, help_text='User recipient. Null if sent to passenger without account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.transportationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
